### ISSUE TITLE
Unexpected docker daemon stops

### ISSUE THREAD

**Issue by mortum5** [graphprotocol/hardhat-graph-demo#2]
I follow the README.md guide for deploy contracts and run subgraph, and it runs, but in playground i can see just this message

```sh
{
  "errors": [ 
    "{"errors": ["message\": \"Store error: query execution failed: Subgraph QmdpxmJ5bfHGPQgKmWNeqLh7HEtSXn4NCY5i6449qS5gka has not started syncing yet. Wait for it to ingest a few blocks before querying it\"}"
  ]
}
```

And after several minutes docker daemons stop answers and in log show this error message.

```sh
Exception in thread Thread-10:
Traceback (most recent call last):
  File "docker/utils/json_stream.py", line 78, in split_buffer
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "compose/cli/log_printer.py", line 202, in watch_events
  File "compose/project.py", line 613, in yield_loop
  File "docker/types/daemon.py", line 32, in __next__
  File "docker/api/client.py", line 344, in _stream_helper
  File "docker/utils/json_stream.py", line 80, in split_buffer
docker.errors.StreamParseError: Expecting value: line 1 column 1 (char 0)
Unexpected API error for hardhat-graph-demo_graph-node_1 (HTTP code 502)
Response body:
Bad response from Docker engine

Unexpected API error for hardhat-graph-demo_postgres_1 (HTTP code 502)
Response body:
Bad response from Docker engine

Unexpected API error for hardhat-graph-demo_ipfs_1 (HTTP code 502)
Response body:
Bad response from Docker engine
```

Also first i`ve encounter this problem when i try create the same by myself and run ganache, deploy my project contract.
I use
Docker v4.13.0
MacOS 13

**Comment by dimitrovmaksim** [comment]
Try downgrading docker to v4.10.0. I had the same issue with graph-node on newer versions

**Comment by mortum5** [comment]
> Try downgrading docker to v4.10.0. I had the same issue with graph-node on newer versions

Thank you, i upgrade instead of downgrade to v4.16.0 and now it works without crushs, but i cant received any data from graphiql, it's show error message about `has not started syncing yet.` and it lasts anout 5 minutes already, is it bug or not?

**Comment by dimitrovmaksim** [comment]
Try by stopping the graph-node and clear the cached data by running `npm run/yarn graph-local-clean`. Start it again, add a startBlock to the datasource and deploy the subgraph again

https://github.com/graphprotocol/hardhat-graph#running-local-graph-node-against-local-hardhat-node

**Comment by mortum5** [comment]
Thank you! I will try
